# Generated by Django 5.2.4 on 2025-07-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('korean', models.CharField(max_length=100)),
                ('english', models.CharField(max_length=100)),
            ],
        ),
    ]
